const projects=[
{id:"coffee",name:"Neighborhood Coffee Studio",city:"Austin",region:"Texas",country:"United States",category:"Food & Beverage",score:78,stage:"Demo",summary:"A compact specialty coffee concept designed around repeat local demand and disciplined operating costs.",signals:["Local demand","Repeat purchase","Operational complexity"],risks:["Lease economics","Labor intensity","Site selection"]},
{id:"auto",name:"Mobile Auto Detailing",city:"Tampa",region:"Florida",country:"United States",category:"Services",score:84,stage:"Demo",summary:"A mobile service model that avoids a traditional storefront and can start with a focused service menu.",signals:["Low fixed footprint","Convenience","Service upsell"],risks:["Customer acquisition","Route density","Seasonality"]},
{id:"bakery",name:"Micro Bakery",city:"Manchester",region:"England",country:"United Kingdom",category:"Food & Beverage",score:73,stage:"Demo",summary:"A small-format bakery model focused on a narrow product range and pre-order demand.",signals:["Pre-orders","Niche positioning","Small menu"],risks:["Production capacity","Food compliance","Waste"]},
{id:"cleaning",name:"Premium Home Cleaning",city:"Toronto",region:"Ontario",country:"Canada",category:"Services",score:81,stage:"Demo",summary:"A recurring residential service model with room to build repeat customers and standardized operations.",signals:["Recurring demand","Standardization","Upsells"],risks:["Hiring","Retention","Local competition"]},
{id:"fitness",name:"Boutique Fitness Studio",city:"Melbourne",region:"Victoria",country:"Australia",category:"Health & Fitness",score:69,stage:"Demo",summary:"A premium small-group fitness concept where location, retention and instructor quality drive outcomes.",signals:["Membership potential","Community","Premium positioning"],risks:["High fixed costs","Retention","Instructor dependency"]},
{id:"print",name:"B2B Print & Sign Studio",city:"Dubai",region:"Dubai",country:"United Arab Emirates",category:"B2B Services",score:76,stage:"Demo",summary:"A business-to-business production service serving recurring signage, print and branding needs.",signals:["B2B repeat orders","Cross-sell","Local relationships"],risks:["Equipment capex","Sales cycle","Working capital"]}
];

const app=document.getElementById("app");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function card(p){return `<article class="card"><span class="tag">${esc(p.category)} · ${p.stage}</span><h3>${esc(p.name)}</h3><div class="location">${esc(p.city)}, ${esc(p.region)}, ${esc(p.country)}</div><p class="muted">${esc(p.summary)}</p><div class="card-foot"><div class="small-score">${p.score}<span>/100</span></div><a class="btn secondary" href="#/project/${p.id}">View project</a></div></article>`}
function layout(body){app.innerHTML=body;window.scrollTo(0,0)}
function home(){layout(`<div class="wrap"><section class="hero"><div><div class="eyebrow">WorthBuild · From Idea to Profit</div><h1>Know if it’s <em>worth</em> your money.</h1><p>Research a business concept, understand the key risks, compare opportunities, and only then decide what to build.</p><div class="actions"><a class="btn" href="#/explore">Explore businesses</a><a class="btn secondary" href="#/worth-it">Test my idea</a></div></div><div class="proof"><div class="eyebrow">Illustrative demo</div><div class="score">78<span>/100</span></div><div class="meter"><i style="width:78%"></i></div><p class="muted">WorthScore combines market fit, economics, execution difficulty and risk signals. Demo scores are not verified investment advice.</p><div class="mini-grid"><div class="mini"><b>6</b><span>demo projects</span></div><div class="mini"><b>Global</b><span>country → city</span></div></div></div></section>
<section><div class="section-head"><div><div class="eyebrow">Explore</div><h2>Projects worth investigating</h2></div><a href="#/explore" class="muted">View all →</a></div><div class="cards">${projects.slice(0,3).map(card).join("")}</div></section>
<section><div class="banner"><div><div class="eyebrow">Not sure what to build?</div><h2>Tell us what you want. We’ll narrow the field.</h2></div><a class="btn" href="#/match">Help me choose →</a></div></section>
<section><div class="section-head"><div><div class="eyebrow">The principle</div><h2>Trust before hype.</h2><p>WorthBuild is designed around evidence. Until verified source data is available, project figures are explicitly marked as demo or evidence-pending.</p></div></div></section></div>`)}
function explore(){layout(`<div class="wrap"><section><div class="eyebrow">Explore Businesses</div><h1>Find a business worth investigating.</h1><p class="muted">Filter by geography and category. Global hierarchy: country → region/state → city.</p><div class="filters"><input id="q" class="input" placeholder="Search business, city or country…"><select id="cat" class="select"><option>All categories</option>${[...new Set(projects.map(p=>p.category))].map(x=>`<option>${esc(x)}</option>`).join("")}</select></div><div id="results" class="cards">${projects.map(card).join("")}</div></section></div>`);const render=()=>{let q=document.getElementById("q").value.toLowerCase(),c=document.getElementById("cat").value;document.getElementById("results").innerHTML=projects.filter(p=>(!q||JSON.stringify(p).toLowerCase().includes(q))&&(c==="All categories"||p.category===c)).map(card).join("")||`<div class="empty">No projects found.</div>`};document.getElementById("q").oninput=render;document.getElementById("cat").onchange=render}
function project(id){let p=projects.find(x=>x.id===id);if(!p)return home();let factors=[["Market fit",Math.max(55,p.score+2)],["Economics",Math.max(50,p.score-3)],["Execution",Math.max(48,p.score-7)],["Risk profile",Math.max(45,p.score+1)]];layout(`<div class="detail"><a class="muted" href="#/explore">← Back to Explore</a><div class="detail-top"><div><span class="tag">${esc(p.category)} · ${p.stage}</span><h1>${esc(p.name)}</h1><p class="muted">${esc(p.city)}, ${esc(p.region)}, ${esc(p.country)}</p><p>${esc(p.summary)}</p></div><div><div class="big-score">${p.score}</div><div class="muted">WorthScore / 100</div></div></div><div class="notice">Demo analysis only. This page does not represent verified financial performance, expected profit, or a guarantee of success.</div><div class="panel"><h2>WorthScore breakdown</h2>${factors.map(([n,v])=>`<div class="row"><div><strong>${n}</strong><span class="muted">Evidence status: pending verification</span></div><div><b>${v}</b><div class="meter"><i style="width:${v}%"></i></div></div></div>`).join("")}</div><div class="panel"><h2>What to validate</h2><div class="cards">${p.signals.map(x=>`<div class="mini"><b>${esc(x)}</b><span>Validation signal</span></div>`).join("")}</div><h3>Key risks</h3><ul>${p.risks.map(x=>`<li class="muted">${esc(x)}</li>`).join("")}</ul></div><div class="actions"><a class="btn" href="#/room/${p.id}">Open Project Room</a><a class="btn secondary" href="#/compare">Compare</a></div></div>`)}
function match(){layout(`<div class="wrap"><section><div class="eyebrow">Help Me Choose</div><h1>What kind of business fits you?</h1><p class="muted">A lightweight matching tool for the MVP. It narrows the demo catalog; it is not financial advice.</p><div class="panel"><label>Prefer low fixed costs?</label><select id="fixed" class="select"><option>Yes</option><option>No</option></select><br><br><label>Business type</label><select id="type" class="select"><option>Any</option><option>Services</option><option>Food & Beverage</option><option>B2B Services</option><option>Health & Fitness</option></select><br><br><button class="btn" id="go">Find matches</button></div><div id="matches" class="cards" style="margin-top:20px"></div></section></div>`);document.getElementById("go").onclick=()=>{let t=document.getElementById("type").value;let r=projects.filter(p=>t==="Any"||p.category===t).sort((a,b)=>b.score-a.score).slice(0,3);document.getElementById("matches").innerHTML=r.map(card).join("")||`<div class="empty">No demo match.</div>`}}
function worth(){layout(`<div class="wrap"><section><div class="eyebrow">Worth It?</div><h1>Stress-test your idea before spending.</h1><div class="panel"><input id="idea" class="input" placeholder="Example: mobile coffee cart in my city"><button class="btn" id="analyze">Analyze idea</button></div><div id="analysis"></div></section></div>`);document.getElementById("analyze").onclick=()=>{let idea=document.getElementById("idea").value.trim();if(!idea)return;document.getElementById("analysis").innerHTML=`<div class="panel"><div class="eyebrow">Preliminary result</div><h2>${esc(idea)}</h2><div class="notice">WorthBuild cannot responsibly claim profitability from an idea alone. The next step is evidence collection: target customer, local competition, startup cost, pricing, demand proof and operating constraints.</div><div class="steps" style="margin-top:20px"><div class="step"><span class="num">01</span><h3>Demand</h3><p>Who will pay, how often, and what proof exists?</p></div><div class="step"><span class="num">02</span><h3>Economics</h3><p>Estimate startup and recurring costs using real local inputs.</p></div><div class="step"><span class="num">03</span><h3>Execution</h3><p>Identify permits, skills, suppliers and operational bottlenecks.</p></div></div></div>`}}
function compare(){layout(`<div class="wrap"><section><div class="eyebrow">Compare</div><h1>Put opportunities side by side.</h1><div class="panel"><table class="table"><thead><tr><th>Project</th><th>Location</th><th>Category</th><th>WorthScore</th></tr></thead><tbody>${projects.map(p=>`<tr><td><a href="#/project/${p.id}"><b>${esc(p.name)}</b></a></td><td>${esc(p.city)}, ${esc(p.country)}</td><td>${esc(p.category)}</td><td><b>${p.score}</b>/100</td></tr>`).join("")}</tbody></table></div></section></div>`)}
function how(){layout(`<div class="wrap"><section><div class="eyebrow">How it works</div><h1>From idea to an informed decision.</h1><div class="steps"><div class="step"><span class="num">01</span><h3>Discover</h3><p>Browse business concepts by country, region and city.</p></div><div class="step"><span class="num">02</span><h3>Evaluate</h3><p>Review WorthScore, assumptions, evidence status and risks.</p></div><div class="step"><span class="num">03</span><h3>Build</h3><p>Use the Project Room to turn a validated concept into an execution plan.</p></div></div></section></div>`)}
function room(id){let p=projects.find(x=>x.id===id)||projects[0];layout(`<div class="detail"><div class="eyebrow">Project Room · Demo</div><h1>${esc(p.name)}</h1><div class="panel"><h2>Build checklist</h2><div class="steps"><div class="step"><span class="num">01</span><h3>Market evidence</h3><p>Collect local demand and competitor evidence.</p></div><div class="step"><span class="num">02</span><h3>Unit economics</h3><p>Enter verified startup, operating and pricing assumptions.</p></div><div class="step"><span class="num">03</span><h3>Launch plan</h3><p>Suppliers, permits, offer, acquisition and first 90 days.</p></div></div></div><div class="panel"><h2>Premium build system</h2><p class="muted">This is the future paid layer: templates, financial model, launch checklist, supplier research, marketing system and decision dashboard.</p><a class="btn" href="#/checkout">Unlock the system</a></div></div>`)}
function checkout(){layout(`<div class="wrap"><section><div class="eyebrow">Checkout · UI Preview</div><h1>Build the business with a system.</h1><div class="panel"><h2>WorthBuild Business Launch System</h2><p class="muted">Premium product placeholder for the MVP.</p><ul class="muted"><li>Decision & validation framework</li><li>Startup budget template</li><li>90-day launch roadmap</li><li>Marketing & operations checklists</li><li>Project Room workspace</li></ul><div class="notice">Payments are not connected in this demo build.</div><br><button class="btn" onclick="alert('Checkout is a demo UI. Payment integration comes next.')">Continue to payment</button></div></section></div>`)}
function route(){let h=location.hash||"#/";let a=h.slice(2).split("/");if(a[0]==="")return home();if(a[0]==="explore")return explore();if(a[0]==="project")return project(a[1]);if(a[0]==="match")return match();if(a[0]==="worth-it")return worth();if(a[0]==="compare")return compare();if(a[0]==="how-it-works")return how();if(a[0]==="room")return room(a[1]);if(a[0]==="checkout")return checkout();home()}
window.addEventListener("hashchange",route);route();
